### ISSUE TITLE
Add TSDoc linting

### ISSUE THREAD

**Issue by haroldwaters** [flocasts/nestjs-google-pubsub-connector#25]
**Is your feature request related to a problem? Please describe.**
Auto generated docs will rely on clear and consistent TSDoc comments through out

**Describe the solution you'd like**
TSDoc lint rules should be added

**Comment by william-reynolds-flosports** [comment]
Using this as the issue to publish docs to github pages. @haroldwaters I don't think I have the necessary permissions to enable github pages on this repo so you may have to do that.
