### ISSUE TITLE
Subscription `pushEndpoint` Support

### ISSUE THREAD

**Issue by j** [flocasts/nestjs-google-pubsub-connector#56]
We use Google Cloud Run with PubSub and utilize push endpoints (URL mapping) for handling subscriptions 

```typescript
topic.createSubscription('...', { pushEndpoint: '...' });
```

So instead of listening with a single instance for events, we utilize Cloud Run & its scaling features to handle messages.

With that said, does this library support this?

**Comment by haroldwaters** [comment]
The server component in this library routes messages from events emitted by an internal `PubSub` client - it doesn't map to the use-case you've described. The client portion should work however, though it's just a wrapper for existing functionality.
